export const BASE_FIELDS = {
  content: {
    title: "标题",
    slug: "Slug",
    type: "内容类型",
    category: "分类",
    summary: "摘要",
    recommendationReason: "推荐理由",
    coverImage: "封面图片",
    tags: "标签",
    audience: "适用人群",
    scenario: "适用场景",
    originalUrl: "原始链接",
    feishuDocumentUrl: "飞书文档链接",
    sourceName: "来源名称",
    featured: "首页精选",
    sortWeight: "排序权重",
    publishedAt: "发布时间",
    updatedAt: "更新时间",
    publicationStatus: "发布状态",
    publicLevel: "公开级别",
    generatedFromInbox: "来源 Inbox 记录",
    sourceInboxRecordId: "来源收件箱记录ID",
  },
  copyBlock: {
    relatedContent: "关联内容",
    title: "区块标题",
    type: "区块类型",
    language: "语言",
    content: "内容",
    order: "显示顺序",
    note: "备注",
    sourceInboxCopyBlockKey: "来源收件箱复制块键",
  },
  inbox: {
    rawContent: "原始内容",
    editorNote: "编辑备注",
    processingStatus: "处理状态",
    detectedSourceType: "检测来源类型",
    suggestedContentType: "建议内容类型",
    suggestedCategory: "建议分类",
    generatedTitle: "生成标题",
    generatedSummary: "生成摘要",
    generatedRecommendationReason: "生成推荐理由",
    sourceUrl: "来源链接",
    relatedDraftContent: "关联草稿内容",
    errorMessage: "错误信息",
    submittedAt: "提交时间",
    processedAt: "处理时间",
  },
} as const;

export const BASE_VALUES = {
  content: {
    draft: "草稿",
  },
  inbox: {
    pending: "待处理",
    processing: "处理中",
    reviewRequired: "待审核",
    failed: "失败",
  },
} as const;
