export const BASE_FIELDS = {
  content: {
    title: "标题",
    slug: "Slug",
    type: "内容类型",
    category: "分类",
    summary: "摘要",
    recommendationReason: "推荐理由",
    recommendationTrack: "推荐轨道",
    timeToValue: "上手时间",
    adoptionLevel: "使用门槛",
    networkRequirement: "网络要求",
    takeaway: "可带走结果",
    coverImage: "封面图片",
    tags: "标签",
    audience: "适用人群",
    scenario: "适用场景",
    originalUrl: "原始链接",
    feishuDocumentUrl: "飞书文档链接",
    sourceName: "来源名称",
    featured: "首页精选",
    sortWeight: "排序权重",
    publishedAt: "发布时间",
    updatedAt: "更新时间",
    publicationStatus: "发布状态",
    publicLevel: "公开级别",
    generatedFromInbox: "来源 Inbox 记录",
    sourceInboxRecordId: "来源收件箱记录ID",
  },
  copyBlock: {
    relatedContent: "关联内容",
    title: "区块标题",
    type: "区块类型",
    language: "语言",
    content: "内容",
    order: "显示顺序",
    note: "备注",
    sourceInboxCopyBlockKey: "来源收件箱复制块键",
  },
  inbox: {
    rawContent: "原始内容",
    editorNote: "编辑备注",
    processingStatus: "处理状态",
    detectedSourceType: "检测来源类型",
    suggestedContentType: "建议内容类型",
    suggestedCategory: "建议分类",
    generatedTitle: "生成标题",
    generatedSummary: "生成摘要",
    generatedRecommendationReason: "生成推荐理由",
    generatedRecommendationTrack: "生成推荐轨道",
    generatedTimeToValue: "生成上手时间",
    generatedAdoptionLevel: "生成使用门槛",
    generatedTakeaway: "生成可带走结果",
    sourceUrl: "来源链接",
    relatedDraftContent: "关联草稿内容",
    errorMessage: "错误信息",
    submittedAt: "提交时间",
    processedAt: "处理时间",
  },
} as const;

export const PRIVATE_BASE_FIELD_NAMES = {
  content: {
    publicationStatus: BASE_FIELDS.content.publicationStatus,
    publicLevel: BASE_FIELDS.content.publicLevel,
    generatedFromInbox: BASE_FIELDS.content.generatedFromInbox,
    sourceInboxRecordId: BASE_FIELDS.content.sourceInboxRecordId,
  },
  copy: {
    relatedContent: BASE_FIELDS.copyBlock.relatedContent,
    sourceInboxCopyBlockKey: BASE_FIELDS.copyBlock.sourceInboxCopyBlockKey,
  },
  inbox: {
    rawContent: BASE_FIELDS.inbox.rawContent,
    editorNote: BASE_FIELDS.inbox.editorNote,
    processingStatus: BASE_FIELDS.inbox.processingStatus,
    detectedSourceType: BASE_FIELDS.inbox.detectedSourceType,
    suggestedContentType: BASE_FIELDS.inbox.suggestedContentType,
    suggestedCategory: BASE_FIELDS.inbox.suggestedCategory,
    generatedTitle: BASE_FIELDS.inbox.generatedTitle,
    generatedSummary: BASE_FIELDS.inbox.generatedSummary,
    generatedRecommendationReason: BASE_FIELDS.inbox.generatedRecommendationReason,
    generatedRecommendationTrack: BASE_FIELDS.inbox.generatedRecommendationTrack,
    generatedTimeToValue: BASE_FIELDS.inbox.generatedTimeToValue,
    generatedAdoptionLevel: BASE_FIELDS.inbox.generatedAdoptionLevel,
    generatedTakeaway: BASE_FIELDS.inbox.generatedTakeaway,
    sourceUrl: BASE_FIELDS.inbox.sourceUrl,
    relatedDraftContent: BASE_FIELDS.inbox.relatedDraftContent,
    errorMessage: BASE_FIELDS.inbox.errorMessage,
    submittedAt: BASE_FIELDS.inbox.submittedAt,
    processedAt: BASE_FIELDS.inbox.processedAt,
  },
} as const;

export const BASE_VALUES = {
  content: {
    draft: "草稿",
    publicLevels: {
      public: "公开",
      desensitized: "脱敏案例",
      forbidden: "禁止发布",
    },
  },
  inbox: {
    pending: "待处理",
    processing: "处理中",
    reviewRequired: "待审核",
    failed: "失败",
  },
} as const;
